### ISSUE TITLE
Error (Linux): Changes in variable name

### ISSUE THREAD

**Issue by sanskaromar** [CC-MNNIT/proxy-settings#1]
#### For Linux/Mac terminal, temporary solution:
I think following changes should be made to apply changes properly

```diff
- export http_proxy="http://edcguest:edcguest@172.31.100.29:3128"
+ export HTTP_PROXY="http://edcguest:edcguest@172.31.100.29:3128"
- export https_proxy="http://edcguest:edcguest@172.31.100.29:3128"
+ export HTTPS_PROXY="http://edcguest:edcguest@172.31.100.29:3128"
- export all_proxy="http://edcguest:edcguest@172.31.100.29:3128"
+ export ALL_PROXY="http://edcguest:edcguest@172.31.100.29:3128"
```

**Comment by nisiddharth** [comment]
I don't think so.
I remember `wget` only respected settings when they were in lowercase.

They are not very POSIX I suppose.

**Comment by nisiddharth** [comment]
Yes, see the first answer [here](https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca).

> http_proxy, https_proxy, ftp_proxy and no_proxy are commonly lowercase.

At this point, it feels like they have become case insensitive.

**Comment by sanskaromar** [comment]
I reported this because it doesn't work in lowercase in my computer but works in uppercase :crying_cat_face:

**Comment by sanskaromar** [comment]
**What if we run both lowercase and uppercase commands?**

I think most of the programs need them in lowercase as you mentioned but there are some which need them in uppercase. Doing this will cover both cases. 

![image](https://user-images.githubusercontent.com/77530596/141289145-b54a0ae4-3abb-44a1-bb9f-f42c74e4ded4.png)
From the same StackOverflow answer, you mentioned earlier.

**Comment by nisiddharth** [comment]
Sure, since it isn't working for you then it might happen to many. I'll add it.

**Comment by nisiddharth** [comment]
Done, check once and if fine, close the issue :)
